// assetsMap.js
export const assetsMap = {
  "Worm Wyrm": require("./assets/worm_wyrm.gif"),
  "Derpasaurus Rex": require("./assets/derpasaurus_rex.gif"),
  "Messenger bAAAAAUGH": require("./assets/messenger_baugh.gif"),
  "Explode-a-Bear": require("./assets/explode_a_bear.gif"),
  "Knock Off Plant": require("./assets/knock_off_plant.gif"),
  "Standard Bandit": require("./assets/standard_bandit.gif"),
  "Spunky Spooky Skeleton": require("./assets/spunky_spooky_skeleton.gif"),
  "Heckle Boo": require("./assets/heckle_boo.gif"),
  Barbarian: require("./assets/barbarian.gif"),
  Bard: require("./assets/bard.gif"),
  Cleric: require("./assets/cleric.gif"),
  Druid: require("./assets/druid.gif"),
  Fairy: require("./assets/fairy.gif"),
  Knight: require("./assets/knight.gif"),
  Monk: require("./assets/monk.gif"),
  Sorcerer: require("./assets/sorcerer.gif"),
  "Walking Wizard": require("./assets/walking_wizard.gif"),
  Cave: require("./assets/cave.jpg"),
  "Whale Infested Waters": require("./assets/whale_infested_waters.jpg"),
  "Small Questing Town": require("./assets/small_questing_town.jpg"),
  "Mermaid Spring": require("./assets/mermaid_spring.jpg"),
  "Mysterious Temple": require("./assets/mysterious_temple.jpg"),
  "Haunted Forest": require("./assets/haunted_forest.jpg"),
  "Abandoned Village": require("./assets/abandoned_village.jpg"),
  "Mysterious Tower": require("./assets/mysterious_tower.jpg"),
  "Enchanted Garden": require("./assets/enchanted_garden.jpg"),
  "Sentient Explosive Chew Toy": require("./assets/sentient_explosive_chewtoy.gif"),
  "Sentient Carrot": require("./assets/sentient_carrrot.gif"),
  Octobat: require("./assets/octobat.gif"),
  "Canadian Goose": require("./assets/canadian_goose.gif"),
  "Pasta Pelican": require("./assets/pasta_pelican.gif"),
  "Uncanny Turkey": require("./assets/uncanny_turkey.gif"),
  "Possessed Dinosaur Floaty": require("./assets/possessed_dinosaur_floaty.gif"),
  "Fish Plane": require("./assets/fish_plane.gif"),
  "Outdoor Cat Tavern": require("./assets/outdoor_cat_tavern.jpg"),
  "Captain Chonkers": require("./assets/captain_chonkers.gif"),
  "The Noodle Guy": require("./assets/the_noodle_guy.jpg"),
  "Bad Hair StoreKeep": require("./assets/bad_hair_storekeep.gif"),
  "Dancing Mermaid": require("./assets/dancing_mermaid.gif"),
  "Disco Wizard": require("./assets/disco_wizard.gif"),
  "Tutorial KNPC": require("./assets/tutorial_knpc.gif"),
};
